url: http://var7.github.io
baseurl: /vj-landingpage/

# Site settings
title: Vivek Jonnalagadda
email: jvvp1994@gmail.com
description: "Football CV for Vivek Jonnalagadda"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3385FF
  secondary: 3399FF
  secondary-dark: 333

# Team names, titles and social links
##people:
-# name: Kay Garland
 # pic: 1
 # position: Lead Designer
 # social:
 #   - title: twitter
 #     url: #
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: www.facebook.com
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Hyderabad
  - line: India

# Build settings
markdown: kramdown
permalink: pretty